# Generated by Django 4.2.20 on 2025-07-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('application_link', models.TextField()),
                ('source', models.TextField()),
                ('amount', models.TextField()),
                ('deadline', models.TextField()),
                ('course', models.TextField()),
                ('gpa', models.TextField()),
                ('location', models.TextField()),
                ('scraped_at', models.DateTimeField()),
            ],
        ),
    ]
