# Generated by Django 4.2.20 on 2025-07-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_userscholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
