# Generated by Django 5.2.4 on 2025-08-03 08:23

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_fix_scholarship_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ['-scraped_at']},
        ),
        migrations.RemoveIndex(
            model_name='scholarship',
            name='scholarship_active_deadline_idx',
        ),
        migrations.RenameIndex(
            model_name='scholarship',
            new_name='scholarship_deadlin_f24616_idx',
            old_name='scholarship_deadline_idx',
        ),
        migrations.RenameIndex(
            model_name='scholarship',
            new_name='scholarship_amount_dbe338_idx',
            old_name='scholarship_amount_idx',
        ),
        migrations.RenameIndex(
            model_name='scholarship',
            new_name='scholarship_gpa_c7aad6_idx',
            old_name='scholarship_gpa_idx',
        ),
        migrations.RenameIndex(
            model_name='scholarship',
            new_name='scholarship_degree__a1e784_idx',
            old_name='scholarship_degree_level_idx',
        ),
        migrations.RenameIndex(
            model_name='scholarship',
            new_name='scholarship_locatio_9ec84c_idx',
            old_name='scholarship_location_idx',
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount_currency',
            field=models.CharField(blank=True, default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='application_link',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='course',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('4.00'))]),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='source',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scholarshipprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scholarshipprofile',
            name='financial_need',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='scholarshipprofile',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('4.00'))]),
        ),
        migrations.AlterField(
            model_name='scholarshipprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
