# Generated by Django 4.2.20 on 2025-06-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_document_parsedprofile_usergoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
