# Generated by Django 5.2.1 on 2025-07-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user'),
        ('users', '0005_alter_educationprofile_options_and_more'),
    ]

    operations = [
    ]
