# Generated by Django 4.2.20 on 2025-07-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20250702_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
