# Generated by Django 4.2.20 on 2025-07-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_cv_file_userprofile_cv_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
