# Generated by Django 5.2.4 on 2025-07-24 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('course', models.CharField(blank=True, max_length=255)),
                ('degree_level', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('financial_need', models.CharField(blank=True, max_length=100)),
                ('deadline_proximity', models.IntegerField(blank=True, null=True)),
                ('eligibility_tags', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scholarship Profile',
                'verbose_name_plural': 'Scholarship Profiles',
                'ordering': ['user__email'],
            },
        ),
    ]
