# Generated by Django 5.2.4 on 2025-08-03 08:23

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='gcs_bucket_name',
            field=models.CharField(blank=True, help_text='GCS bucket name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='gcs_path',
            field=models.CharField(blank=True, help_text='Path to document in Google Cloud Storage', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='gcs_public_url',
            field=models.URLField(blank=True, help_text='Public URL for document in GCS', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_gcs_path',
            field=models.CharField(blank=True, help_text='Path to CV file in Google Cloud Storage', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_public_url',
            field=models.URLField(blank=True, help_text='Public URL for CV file in GCS', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when CV was uploaded to GCS', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Legacy file storage - deprecated', null=True, upload_to=users.models.document_upload_path, validators=[users.models.validate_document_format, users.models.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv_file',
            field=models.BinaryField(blank=True, help_text='Legacy binary storage - deprecated', null=True),
        ),
    ]
