# Generated by Django 5.2.4 on 2025-08-03 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_fix_job_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_at']},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='job_posted_at_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_title_0e1e41_idx',
            old_name='job_title_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_company_73ae7f_idx',
            old_name='job_company_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_locatio_8b2f8c_idx',
            old_name='job_location_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_job_typ_f6c220_idx',
            old_name='job_type_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_experie_09027f_idx',
            old_name='job_experience_level_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_is_remo_78fc35_idx',
            old_name='job_remote_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_is_acti_b6ae73_idx',
            old_name='job_active_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_source_e2155e_idx',
            old_name='job_source_idx',
        ),
        migrations.RenameIndex(
            model_name='userjob',
            new_name='jobs_userjo_user_id_24062c_idx',
            old_name='userjob_user_applied_idx',
        ),
        migrations.RenameIndex(
            model_name='userjob',
            new_name='jobs_userjo_status_87a4fc_idx',
            old_name='userjob_status_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
