"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import logging
from dotenv import load_dotenv
from urllib.parse import urlparse

# Configure logging before using it
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

load_dotenv()
from pathlib import Path

# Setup Google Cloud credentials early in Django startup
from utils.google_credentials import setup_google_credentials
setup_google_credentials()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        'DJANGO_SECRET_KEY environment variable is required. '
        'Please set it in your environment variables.'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Security settings
if not DEBUG:
    # Production security settings
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

    # Additional security headers
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # Development settings
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'ha-backend-pq2f.vercel.app', '.vercel.app', '.huesapply.com']

SITE_ID = 1

AUTH_USER_MODEL = 'users.CustomUser'

# Google OAuth Settings
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID')
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET')

# Environment-aware redirect URI
# NOTE: When using authorization code flow from JavaScript, Google expects 'postmessage' as redirect_uri
# The backend endpoint redirect URI is only used for debugging/reference
if DEBUG:
    default_redirect = 'http://localhost:8000/api/auth/google/callback/'
else:
    default_redirect = 'https://backend.huesapply.com/api/auth/google/callback/'

GOOGLE_OAUTH_REDIRECT_URI = os.environ.get('GOOGLE_OAUTH_REDIRECT_URI', default_redirect)

# For compatibility with existing code, also set these as GOOGLE_CLIENT_ID/SECRET
GOOGLE_CLIENT_ID = GOOGLE_OAUTH_CLIENT_ID
GOOGLE_CLIENT_SECRET = GOOGLE_OAUTH_CLIENT_SECRET

# Google Cloud Storage Settings
GCS_BUCKET_NAME = os.environ.get('GCS_BUCKET_NAME', 'huesapply-user_documents')

# Graceful OAuth validation - warn but don't crash
GOOGLE_OAUTH_ENABLED = True
if not GOOGLE_OAUTH_CLIENT_ID:
    logger.warning(
        'GOOGLE_OAUTH_CLIENT_ID not found. Google OAuth will be disabled. '
        'Set GOOGLE_OAUTH_CLIENT_ID environment variable to enable.'
    )
    GOOGLE_OAUTH_ENABLED = False

if not GOOGLE_OAUTH_CLIENT_SECRET:
    logger.warning(
        'GOOGLE_OAUTH_CLIENT_SECRET not found. Google OAuth will be disabled. '
        'Set GOOGLE_OAUTH_CLIENT_SECRET environment variable to enable.'
    )
    GOOGLE_OAUTH_ENABLED = False

# Frontend URL for redirecting after OAuth flow
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'opportunities',
    'django.contrib.sites',
    'users',
    'scholarships',
    'jobs',
]




REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Enable for admin/debugging
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Anonymous users: 100 requests per hour
        'user': '1000/hour',  # Authenticated users: 1000 requests per hour
        'burst': '60/minute',  # Burst rate: 60 requests per minute
        'sustained': '1000/hour',  # Sustained rate: 1000 requests per hour
    }
}

# Simple JWT Settings - Using separate signing key for security
from datetime import timedelta

# JWT Signing Key - separate from Django SECRET_KEY for security
JWT_SIGNING_KEY = os.environ.get('JWT_SIGNING_KEY', SECRET_KEY)
if JWT_SIGNING_KEY == SECRET_KEY:
    logger.warning(
        'Using Django SECRET_KEY for JWT signing. Set JWT_SIGNING_KEY environment variable '
        'for better security and key rotation capabilities.'
    )

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # Reduced from 7 days
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',  # Use HMAC SHA256 instead of RSA algorithms
    'SIGNING_KEY': JWT_SIGNING_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'UPDATE_LAST_LOGIN': True,  # Track last login
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise middleware for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware - must come before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # React default port
    "http://127.0.0.1:5173",
    "https://dev.huesapply.com",
    "https://huesapply.com",
    "https://www.huesapply.com",
    # Add your frontend production URL when deploying
]

# Additional CORS settings for OAuth and API access
CORS_ALLOW_ALL_HEADERS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Additional CORS settings for preflight requests
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# For development, you can also allow all origins (NOT recommended for production)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

#Social login settings

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP' : {
            'client_id' : GOOGLE_CLIENT_ID,
            'secret' : GOOGLE_CLIENT_SECRET,
        },
        'SCOPE' : ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'METHOD': 'oauth2',
        'VERIFIED_EMAIL' : True,
    },
}

SOCIALACCOUNT_LOGIN_ON_GET=True
LOGIN_REDIRECT_URL= 'account'


# Database

# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Add these at the top of your settings.py

# Replace the DATABASES section of your settings.py with this

# change the DATABASE_URL to your database URL in your .env file
# DATABASE_URL=postgres://USER:PASSWORD@HOST:PORT/NAME


# DO NOT CHANGE THIS
# DATABASE_URL = os.getenv('DATABASE_URL', 'postgres://nezer_admin:MynameisNezer95.@localhost:5432/ha_db')

DATABASE_URL = os.getenv('DATABASE_URL')
url = urlparse(DATABASE_URL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': url.path[1:],
        'USER': url.username,
        'PASSWORD': url.password,
        'HOST': url.hostname,
        'PORT': url.port,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Enable WhiteNoise for static file serving in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Extra places for collectstatic to find static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
] if os.path.exists(os.path.join(BASE_DIR, 'static')) else []

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'


# Media files - Using GCS instead of local storage for Vercel deployment
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'
