# Generated by Django 4.2.20 on 2025-07-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunity_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='import_batch_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='salary_currency',
            field=models.CharField(blank=True, default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='salary_period',
            field=models.CharField(blank=True, choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('weekly', 'Per Week'), ('monthly', 'Per Month'), ('yearly', 'Per Year')], default='yearly', max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('other', 'Other Source')], default='manual', max_length=50),
        ),
    ]
