# Generated by Django 4.2.20 on 2025-07-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_add_bulk_import_fields'),
        ('opportunities', '0003_opportunity_experience_level'),
    ]

    operations = [
    ]
