# Generated by Django 4.2.20 on 2025-07-16 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_remove_opportunity_posted_by_opportunityapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpportunityApplication',
        ),
    ]
