# Generated by Django 5.2.4 on 2025-08-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_fix_model_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='opportunity',
            name='opportunity_type_deadline_idx',
        ),
        migrations.RemoveIndex(
            model_name='opportunity',
            name='opportunity_location_remote_idx',
        ),
        migrations.RemoveIndex(
            model_name='opportunity',
            name='opportunity_exp_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='opportunity',
            name='opportunity_active_deadline_idx',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='is_active',
        ),
    ]
